#!/bin/bash

inputfile="$1"
filename=$(basename ${inputfile})

# assembles the provided file into a system image for the EPROM programmer
# note: two 32k files will be created to be compatible with my replacement
# system ROM PCB!

dotnet run --project:hp9825utils -- ci private/rom.bin -hl -ovr -n
dotnet run --project:hp9825asm -- "$inputfile" --fromaddress 0 --length 12288 --Beautyfile "private/$filename.out" --fmt:mixedcase --output "private/$filename.bin" --listing "private/$filename.asc" --crossref "private/$filename.xrf" -lh
dotnet run --project:hp9825utils -- mi private/rom.bin "private/$filename.bin" -hl -in:hl --reverse --negate --targetoffset 0 --targetsize 16384 

